### ISSUE TITLE
Cannot install plugins

### ISSUE THREAD

**Issue by joe-gre** [ArchGPT/insomnium#106]
### Expected Behavior

Can install plugins successfully

### Actual Behavior

Plugins fail to load. When clicking "Install Plugin" from the marketplace installation fails and it shows this:
![image](https://github.com/ArchGPT/insomnium/assets/22748761/17f6b91d-d406-4246-8370-e7b02b2dc95c)

When installing a plugin from the Plugins tab in preferences it fails to install and shows this message:
![image](https://github.com/ArchGPT/insomnium/assets/22748761/b580e157-001f-443c-9e3b-605ffd1e2058)

This issue occurs for every plugin I've tried.

### Reproduction Steps

1. Open the Plugins tab in Insomnia preferences
2. Type "insomnia-plugin-save-variables" in the text box, or the name of another plugin
3. Click "Install Plugin"

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/ArchGPT/insomnium/issues) for this problem.

### Insomnium Version

v0.2.3-a

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Build 19045

### Installation method

.exe

### Last Known Working Insomnium version

N/A

**Comment by TCB13** [comment]
+1

**Comment by techchrism** [comment]
This is an issue in Insomnia as well.

The underlying problem is yarn searching parent directories for `package.json` files. Note that ignoring yarn warnings will not solve this issue as a malformed json will trigger a yarn error.

Your reproduction steps are insufficient to reproduce the problem. To reproduce the problem, before step 3, write `{}` to a `package.json` file in any parent directory (the user home directory, for example).

To fix the issue on an individual basis, find and remove the offending `package.json` by traversing parent directories.

**Comment by joe-gre** [comment]
Thanks you're right, there was a package.json file in my user directory for some reason. I deleted it and am now able to install plugins.
