### ISSUE TITLE
cannot install plugin in 

### ISSUE THREAD

**Issue by sherryli-1214** [ArchGPT/insomnium#49]
### Expected Behavior

can install plugin in from plugin management

### Actual Behavior

Failed to install 

There may be an issue with the plugin itself, as a note you can discover and install plugins from the [Plugin Hub.](https://insomnia.rest/plugins)
Additional Information

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/ArchGPT/insomnium/issues) for this problem.

### Insomnium Version

Insomnium 0.2.1-b 

### What operating system are you using?

macOS

### Operating System Version

13.6 (22G120)

### Installation method

download it

**Comment by sherryli-1214** [comment]
rror: Error invoking remote method 'installPlugin': Error: Yarn error {"type":"error","data":"Couldn't find a package.json file in \"/\""}

    at a.invoke (node:electron/js2c/renderer_init:2:7723)
    at async onSubmit (file:///Applications/Insomnium.app/Contents/Resources/app.asar/index-e5e8515f.js:188:513)

**Comment by archywillhe** [comment]
thx for reporting; hmm I'm not able to replicate this; can you give more info on the plugin you are trying to install ?

**Comment by sherryli-1214** [comment]
Thank you. It is Save Variables. 
Just confused the plugin is still from insomnia,right?  Do you keep any plugin in your repo? Thanks.

**Comment by archywillhe** [comment]
Yeah; Insomnia plug-in should still work since it does the same scanning of the repo after cloning it into the data directory.

<img width="765" alt="Screenshot 2023-10-17 at 1 41 16 PM" src="https://github.com/ArchGPT/insomnium/assets/10269911/eec5b8d1-d682-42ac-a1a9-116ecd1ebeb8">

<img width="741" alt="Screenshot 2023-10-17 at 1 42 01 PM" src="https://github.com/ArchGPT/insomnium/assets/10269911/88246e11-b02e-4c8f-988f-b5562504d523">

I'm able to install Save-Variables and get it working in 0.2.1-b.

I think the error you see is likely caused by a typo, etc, in the url (so it can't find the `package.json`). Or could also be a Windows-specific problem? I'll keep an eye on this

**Comment by sherryli-1214** [comment]
Thank you 
Previously i can just search" save variables "in isomnia and plugin, but in insomnium, the name must be very exact .

It is quite weird , even I still can search "save variables" in insomnium(not exactly match), but the error will occured if i click install.

Let's close this issue and will contact you if any other issues. Thank you so much.

**Comment by archywillhe** [comment]
aw I see; look like search is not functioning - I will need to investigate more

**Comment by joe-gre** [comment]
I'm unable to install the sane "save variables" plugin. I typed the name and clicked "Install Plugin" and get this error:
![image](https://github.com/ArchGPT/insomnium/assets/22748761/bbe06ca5-56ca-476e-82d3-be4e7b6c20ed)
